### ISSUE TITLE
Using day name (EEE) in system default date causes crashes...

### ISSUE THREAD

**Issue by Grunthos** [eleybourn/Book-Catalogue#712]
STACK_TRACE=java.lang.IllegalArgumentException: Bad pattern character 'E' in E, d MMM yyyy
at libcore.icu.ICU.getDateFormatOrder(ICU.java:165)
at android.text.format.DateFormat.getDateFormatOrder(DateFormat.java:384)
at com.eleybourn.bookcatalogue.dialogs.PartialDatePicker.reorderPickers(PartialDatePicker.java:488)
at com.eleybourn.bookcatalogue.dialogs.PartialDatePicker.<init>(PartialDatePicker.java:119)
at com.eleybourn.bookcatalogue.dialogs.PartialDatePicker.<init>(PartialDatePicker.java:93)
at com.eleybourn.bookcatalogue.dialogs.PartialDatePickerFragment.onCreateDialog(PartialDatePickerFragment.java:95)
at android.support.v4.app.DialogFragment.getLayoutInflater(DialogFragment.java:295)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:911)
at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1088)
at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1444)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:429)
at android.os.Handler.handleCallback(Handler.java:808)
at android.os.Handler.dispatchMessage(Handler.java:103)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5312)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
at dalvik.system.NativeStart.main(Native Method)

**Comment by Grunthos** [comment]
Fixed in beta; this results from code outside of our control, so we catch and ignore date order for the date picker.
