### ISSUE TITLE
trying to Import Archive, keeps crashing

### ISSUE THREAD

**Issue by bookjim17** [eleybourn/Book-Catalogue#767]
To all,

So, my phone failed on me, or was failing. I copied the entire folder to my pc, did a factory reboot, and moved it all back.

Every time I Import Archive it crashed, I got this info:
USER_COMMENT=trying to Import Archive and it crashes when I choose it
USER_APP_START_DATE=2017-04-24T11:26:44.000-04:00
USER_CRASH_DATE=2017-04-24T11:27:21.000-04:00
APP_VERSION_NAME=5.2.0
APP_VERSION_CODE=177
ANDROID_VERSION=6.0.1
PHONE_MODEL=SM-G900V
CUSTOM_DATA=History-6 = 2017-04-24 15:27:10: BooklistPseudoCursor Created com.eleybourn.bookcatalogue.booklist.BooklistPseudoCursor@254ed68 Running
History-8 = 2017-04-24 15:27:17: BooksOnBookshelf OnPause (com.eleybourn.bookcatalogue.BooksOnBookshelf@4400719) Exit
History-7 = 2017-04-24 15:27:17: BooksOnBookshelf OnPause (com.eleybourn.bookcatalogue.BooksOnBookshelf@4400719) Enter
History-0 = 2017-04-24 15:27:10: BooksOnBookshelf OnCreate (com.eleybourn.bookcatalogue.BooksOnBookshelf@4400719) Enter
History-4 = 2017-04-24 15:27:10: BooksOnBookshelf OnResume (com.eleybourn.bookcatalogue.BooksOnBookshelf@4400719) Exit
History-2 = 2017-04-24 15:27:10: BooksOnBookshelf OnCreate (com.eleybourn.bookcatalogue.BooksOnBookshelf@4400719) Exit
Signed-By = f9:40:7c:63:7d:16:bc:8e:cc:9a:34:ba:85:c3:b9:93
History-3 = 2017-04-24 15:27:10: BooksOnBookshelf OnResume (com.eleybourn.bookcatalogue.BooksOnBookshelf@4400719) Enter
History-5 = 2017-04-24 15:27:10: BooklistBuilder build-1 Exit
History-1 = 2017-04-24 15:27:10: BooklistBuilder build-1 Enter

STACK_TRACE=java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
at android.widget.ArrayAdapter.getCount(ArrayAdapter.java:337)
at android.widget.ListView.onMeasure(ListView.java:1177)
at android.view.View.measure(View.java:20151)
at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
at android.view.View.measure(View.java:20151)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:20151)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:747)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
at android.view.View.measure(View.java:20151)
at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
at android.view.View.measure(View.java:20151)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:20151)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:446)
at android.view.View.measure(View.java:20151)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6330)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3158)
at android.view.View.measure(View.java:20151)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2594)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1549)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1841)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7397)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
at android.view.Choreographer.doCallbacks(Choreographer.java:695)
at android.view.Choreographer.doFrame(Choreographer.java:631)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7224)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Once or maybe twice it made it to the next screen which said pick which one, or similar, it said:
/storage/emulated/0/bookCatalogue on top, but had nothing below it.

When I use File Manager on my Samsung Galaxy S5, everything I need is in /storage/emulated/0/bookCatalogue; all the jpegs, and more importantly, all the bcbk files.

If someone could point out what I am doing wrong, or whatever, I would appreciate it.

Thanks,

JimL

**Comment by Grunthos** [comment]
Please try the import then go to 'Help'->'Send Information' and send the 
resulting email.

**Comment by bookjim17** [comment]
I did do that, I think it sent once, once it dumped it in a text, that's why I included it. I will try again and send.
Thanks, 
JimL 
Sent from my Verizon 4G LTE smartphone

-------- Original message --------

**Comment by Grunthos** [comment]
I have not seen any email on this; pls resend with some link in the subject to this issus id (#767)

**Comment by bookjim17** [comment]
Sorry, I thought I sent you something. I will put it together again and reply to this email.
Thanks for getting back to me.
JimL
Sent from my Verizon 4G LTE smartphone

-------- Original message --------

**Comment by Grunthos** [comment]
On 3/05/2017 10:40 PM, bookjim17 wrote:
> Sorry, I thought I sent you something. I will put it together again and reply 
> to this email.

Rather than doing that, please go to help->Send Information and send the email 
(after causing the problem you are reporting to occur)

**Comment by bookjim17** [comment]
I just sent email like you suggested. It has #767 in the subject. I also sent it to myself. I got the email, and I got notification that it did not go to the Grunthos email. It did go to  the eleybourn email.If you could, please let me know you got the email, I would appreciate it.
Thanks,JimL 


Sent from my Verizon 4G LTE smartphone

-------- Original message --------

**Comment by Grunthos** [comment]
I'm assuming that this is a stable issue
