### ISSUE TITLE
E/WindowManager(16038): android.view.WindowLeaked

### ISSUE THREAD

**Issue by WangGuox1n** [eleybourn/Book-Catalogue#835]
I'm using verison 5.2.0, when testing the app, there is a exception:
STACK_TRACE= E/WindowManager(16038): android.view.WindowLeaked: Activity com.eleybourn.bookcatalogue.booklist.BooklistStylesActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{52990f24 V.E..... R....... 0,0-640,1134} that was originally added here
E/WindowManager(16038): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
E/WindowManager(16038): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
E/WindowManager(16038): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
E/WindowManager(16038): 	at android.app.Dialog.show(Dialog.java:286)
E/WindowManager(16038): 	at com.eleybourn.bookcatalogue.utils.HintManager.displayHint(HintManager.java:155)
E/WindowManager(16038): 	at com.eleybourn.bookcatalogue.booklist.BooklistStylesActivity.onCreate(BooklistStylesActivity.java:80)
E/WindowManager(16038): 	at android.app.Activity.performCreate(Activity.java:5231)
E/WindowManager(16038): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/WindowManager(16038): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
E/WindowManager(16038): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
E/WindowManager(16038): 	at android.app.ActivityThread.access$800(ActivityThread.java:135)
E/WindowManager(16038): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
E/WindowManager(16038): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/WindowManager(16038): 	at android.os.Looper.loop(Looper.java:136)
E/WindowManager(16038): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/WindowManager(16038): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/WindowManager(16038): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/WindowManager(16038): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/WindowManager(16038): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/WindowManager(16038): 	at dalvik.system.NativeStart.main(Native Method)

is it a known issue? wondering is this a bug of BookCatalogue?

**Comment by WangGuox1n** [comment]
second exception: 
**STACK_TRACE**= E/AndroidRuntime( 3979): FATAL EXCEPTION: main
E/AndroidRuntime( 3979): Process: org.liberty.android.fantastischmemo, PID: 3979
E/AndroidRuntime( 3979): java.lang.NullPointerException
E/AndroidRuntime( 3979): 	at com.simplify.ink.InkView.drawBitmap(InkView.java:417)
E/AndroidRuntime( 3979): 	at org.liberty.android.fantastischmemo.ui.PaintActivity$1.run(PaintActivity.java:64)
E/AndroidRuntime( 3979): 	at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 3979): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 3979): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 3979): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime( 3979): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3979): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 3979): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime( 3979): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime( 3979): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by Grunthos** [comment]
See Issue #837
