### ISSUE TITLE
Replace old style dialogs with DialogFragments to preserve state etc on orientation and to close properly

### ISSUE THREAD

**Issue by Grunthos** [eleybourn/Book-Catalogue#837]
This is a large-ish task that will fix a variety of minor errors (ie. errors that cause no data loss). It is a low priority, but needs to be done.

**Comment by anlalalu** [comment]
There are some other similar errors which can be triggered with my automatic testing tool. These are stack traces:

E/WindowManager(23813): 
E/WindowManager(23813): android.view.WindowLeaked: Activity com.eleybourn.bookcatalogue.MainMenu has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{52a67a6c V.E..... R....... 0,0-729,554} that was originally added here
E/WindowManager(23813): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
E/WindowManager(23813): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
E/WindowManager(23813): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
E/WindowManager(23813): 	at android.app.Dialog.show(Dialog.java:286)
E/WindowManager(23813): 	at com.eleybourn.bookcatalogue.utils.AlertDialogUtils.showContextDialogue(AlertDialogUtils.java:86)
E/WindowManager(23813): 	at com.eleybourn.bookcatalogue.MainMenu$1.onClick(MainMenu.java:145)
E/WindowManager(23813): 	at android.view.View.performClick(View.java:4438)
E/WindowManager(23813): 	at android.view.View$PerformClick.run(View.java:18422)
E/WindowManager(23813): 	at android.os.Handler.handleCallback(Handler.java:733)
E/WindowManager(23813): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/WindowManager(23813): 	at android.os.Looper.loop(Looper.java:136)
E/WindowManager(23813): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/WindowManager(23813): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/WindowManager(23813): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/WindowManager(23813): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/WindowManager(23813): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/WindowManager(23813): 	at dalvik.system.NativeStart.main(Native Method)


E/WindowManager(28059): 
E/WindowManager(28059): android.view.WindowLeaked: Activity com.eleybourn.bookcatalogue.BooksOnBookshelf has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{52a04d3c V.E..... R......D 0,0-729,1134} that was originally added here
E/WindowManager(28059): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
E/WindowManager(28059): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
E/WindowManager(28059): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
E/WindowManager(28059): 	at android.app.Dialog.show(Dialog.java:286)
E/WindowManager(28059): 	at com.eleybourn.bookcatalogue.BooksOnBookshelf.doSortMenu(BooksOnBookshelf.java:1287)
E/WindowManager(28059): 	at com.eleybourn.bookcatalogue.BooksOnBookshelf.access$2000(BooksOnBookshelf.java:96)
E/WindowManager(28059): 	at com.eleybourn.bookcatalogue.BooksOnBookshelf$9.run(BooksOnBookshelf.java:1085)
E/WindowManager(28059): 	at com.eleybourn.bookcatalogue.utils.HintManager.displayHint(HintManager.java:111)
E/WindowManager(28059): 	at com.eleybourn.bookcatalogue.BooksOnBookshelf.onMenuItemSelected(BooksOnBookshelf.java:1082)
E/WindowManager(28059): 	at com.actionbarsherlock.ActionBarSherlock.callbackOptionsItemSelected(ActionBarSherlock.java:604)
E/WindowManager(28059): 	at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchOptionsItemSelected(ActionBarSherlockNative.java:92)
E/WindowManager(28059): 	at com.actionbarsherlock.app.SherlockFragmentActivity.onMenuItemSelected(SherlockFragmentActivity.java:204)
E/WindowManager(28059): 	at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1012)
E/WindowManager(28059): 	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:741)
E/WindowManager(28059): 	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
E/WindowManager(28059): 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:884)
E/WindowManager(28059): 	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:874)
E/WindowManager(28059): 	at com.android.internal.view.menu.ActionMenuView.invokeItem(ActionMenuView.java:546)
E/WindowManager(28059): 	at com.android.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:115)
E/WindowManager(28059): 	at android.view.View.performClick(View.java:4438)
E/WindowManager(28059): 	at android.view.View$PerformClick.run(View.java:18422)
E/WindowManager(28059): 	at android.os.Handler.handleCallback(Handler.java:733)
E/WindowManager(28059): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/WindowManager(28059): 	at android.os.Looper.loop(Looper.java:136)
E/WindowManager(28059): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/WindowManager(28059): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/WindowManager(28059): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/WindowManager(28059): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/WindowManager(28059): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/WindowManager(28059): 	at dalvik.system.NativeStart.main(Native Method)


E/WindowManager(31756): 
E/WindowManager(31756): android.view.WindowLeaked: Activity com.eleybourn.bookcatalogue.BookEdit has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{52a07d78 V.E..... R....... 0,0-729,390} that was originally added here
E/WindowManager(31756): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
E/WindowManager(31756): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
E/WindowManager(31756): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
E/WindowManager(31756): 	at android.app.Dialog.show(Dialog.java:286)
E/WindowManager(31756): 	at com.eleybourn.bookcatalogue.dialogs.StandardDialogs.showConfirmUnsavedEditsDialog(StandardDialogs.java:84)
E/WindowManager(31756): 	at com.eleybourn.bookcatalogue.BookEdit.doFinish(BookEdit.java:564)
E/WindowManager(31756): 	at com.eleybourn.bookcatalogue.BookEdit.onOptionsItemSelected(BookEdit.java:1068)
E/WindowManager(31756): 	at android.support.v4.app.Watson.onMenuItemSelected(Watson.java:118)
E/WindowManager(31756): 	at com.actionbarsherlock.ActionBarSherlock.callbackOptionsItemSelected(ActionBarSherlock.java:604)
E/WindowManager(31756): 	at com.actionbarsherlock.internal.ActionBarSherlockNative.dispatchOptionsItemSelected(ActionBarSherlockNative.java:92)
E/WindowManager(31756): 	at com.actionbarsherlock.app.SherlockFragmentActivity.onMenuItemSelected(SherlockFragmentActivity.java:204)
E/WindowManager(31756): 	at com.android.internal.widget.ActionBarView$3.onClick(ActionBarView.java:167)
E/WindowManager(31756): 	at android.view.View.performClick(View.java:4438)
E/WindowManager(31756): 	at android.view.View$PerformClick.run(View.java:18422)
E/WindowManager(31756): 	at android.os.Handler.handleCallback(Handler.java:733)
E/WindowManager(31756): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/WindowManager(31756): 	at android.os.Looper.loop(Looper.java:136)
E/WindowManager(31756): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/WindowManager(31756): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/WindowManager(31756): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/WindowManager(31756): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/WindowManager(31756): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/WindowManager(31756): 	at dalvik.system.NativeStart.main(Native Method)


E/WindowManager(19583): 
E/WindowManager(19583): android.view.WindowLeaked: Activity com.eleybourn.bookcatalogue.UpdateFromInternet has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{52abad04 V.E..... R....... 0,0-777,679} that was originally added here
E/WindowManager(19583): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
E/WindowManager(19583): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
E/WindowManager(19583): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
E/WindowManager(19583): 	at android.app.Dialog.show(Dialog.java:286)
E/WindowManager(19583): 	at com.eleybourn.bookcatalogue.dialogs.StandardDialogs.needLibraryThingAlert(StandardDialogs.java:134)
E/WindowManager(19583): 	at com.eleybourn.bookcatalogue.utils.Utils.showLtAlertIfNecessary(Utils.java:1422)
E/WindowManager(19583): 	at com.eleybourn.bookcatalogue.UpdateFromInternet.onCreate(UpdateFromInternet.java:74)
E/WindowManager(19583): 	at android.app.Activity.performCreate(Activity.java:5231)
E/WindowManager(19583): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/WindowManager(19583): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2148)
E/WindowManager(19583): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
E/WindowManager(19583): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:3724)
E/WindowManager(19583): 	at android.app.ActivityThread.access$900(ActivityThread.java:135)
E/WindowManager(19583): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
E/WindowManager(19583): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/WindowManager(19583): 	at android.os.Looper.loop(Looper.java:136)
E/WindowManager(19583): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/WindowManager(19583): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/WindowManager(19583): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/WindowManager(19583): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/WindowManager(19583): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/WindowManager(19583): 	at dalvik.system.NativeStart.main(Native Method)


E/WindowManager( 7103): 
E/WindowManager( 7103): android.view.WindowLeaked: Activity com.eleybourn.bookcatalogue.StartupActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{529309d0 V.E..... R.....ID 0,0-729,390} that was originally added here
E/WindowManager( 7103): 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:346)
E/WindowManager( 7103): 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:248)
E/WindowManager( 7103): 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
E/WindowManager( 7103): 	at android.app.Dialog.show(Dialog.java:286)
E/WindowManager( 7103): 	at com.eleybourn.bookcatalogue.StartupActivity.stage3Startup(StartupActivity.java:330)
E/WindowManager( 7103): 	at com.eleybourn.bookcatalogue.StartupActivity.stage2Startup(StartupActivity.java:259)
E/WindowManager( 7103): 	at com.eleybourn.bookcatalogue.StartupActivity.taskCompleted(StartupActivity.java:223)
E/WindowManager( 7103): 	at com.eleybourn.bookcatalogue.StartupActivity.access$000(StartupActivity.java:57)
E/WindowManager( 7103): 	at com.eleybourn.bookcatalogue.StartupActivity$3.onTaskFinish(StartupActivity.java:239)
E/WindowManager( 7103): 	at com.eleybourn.bookcatalogue.utils.SimpleTaskQueue.processResults(SimpleTaskQueue.java:440)
E/WindowManager( 7103): 	at com.eleybourn.bookcatalogue.utils.SimpleTaskQueue.access$300(SimpleTaskQueue.java:56)
E/WindowManager( 7103): 	at com.eleybourn.bookcatalogue.utils.SimpleTaskQueue$1.run(SimpleTaskQueue.java:341)
E/WindowManager( 7103): 	at android.os.Handler.handleCallback(Handler.java:733)
E/WindowManager( 7103): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/WindowManager( 7103): 	at android.os.Looper.loop(Looper.java:136)
E/WindowManager( 7103): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/WindowManager( 7103): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/WindowManager( 7103): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/WindowManager( 7103): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/WindowManager( 7103): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/WindowManager( 7103): 	at dalvik.system.NativeStart.main(Native Method)


Most of the errors can be triggered by rotating the screen or press back.

They may be solved with reference to this: https://stackoverflow.com/questions/2850573/activity-has-leaked-window-that-was-originally-added
