### ISSUE TITLE
the app crashes when clicking "ZXing" button

### ISSUE THREAD

**Issue by androidAppGuard** [eleybourn/Book-Catalogue#877]
**the environment is as follows:**
```
App version: v5.2.2
Android version: 6.0
Device: Nexux_5X
```
**The steps to reproduce:**
![12_BookCatalogue_DeadObjectException.gif](https://s2.loli.net/2022/05/13/oIQh1LRix2qDXUJ.gif)
**The exception log is as follows:**
```
05-13 03:48:26.269 2013-2032/system_process W/WindowAnimator: Failed to dispatch window animation state change.
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:503)
        at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
        at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
        at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
        at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
        at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
        at android.view.Choreographer.doFrame(Choreographer.java:603)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.android.server.ServiceThread.run(ServiceThread.java:46)
05-13 03:48:26.269 2013-2032/system_process W/WindowAnimator: Failed to dispatch window animation state change.
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:503)
        at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
        at com.android.server.wm.WindowAnimator.updateWindowsLocked(WindowAnimator.java:286)
        at com.android.server.wm.WindowAnimator.animateLocked(WindowAnimator.java:678)
        at com.android.server.wm.WindowAnimator.-wrap0(WindowAnimator.java)
        at com.android.server.wm.WindowAnimator$1.doFrame(WindowAnimator.java:123)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
        at android.view.Choreographer.doCallbacks(Choreographer.java:670)
        at android.view.Choreographer.doFrame(Choreographer.java:603)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by Grunthos** [comment]
Thank you for the bug report! As a short term work-around, go to the Play Store and install the Zxing scanner manually.

**Comment by Grunthos** [comment]
External scanners no longer required in current version. Will be completely removed in a later release.
