### ISSUE TITLE
Crash when click the PIC2SHOP button

### ISSUE THREAD

**Issue by Terrible-Tornado** [eleybourn/Book-Catalogue#883]
## environment
**Device:** Google Pixel 2
**Android Version:** 9.0
**App Version:** 5.3.0-5

## reproduce
https://user-images.githubusercontent.com/119578731/205843789-d1262bc2-4abf-4e62-816d-78569fbf27bf.mp4

## log
FATAL EXCEPTION: main
    Process: com.eleybourn.bookcatalogue, PID: 24028
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=market://details?id=com.visionsmarts.pic2shop }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2007)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1673)
        at android.app.Activity.startActivityForResult(Activity.java:4586)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at android.app.Activity.startActivityForResult(Activity.java:4544)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
        at android.app.Activity.startActivity(Activity.java:4905)
        at android.app.Activity.startActivity(Activity.java:4873)
        at com.eleybourn.bookcatalogue.BookISBNSearch$18.onClick(BookISBNSearch.java:373)
        at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:172)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by eleybourn** [comment]
Can you try installing the zxing scanner app? Does that work?

TTFN
Evan

**Comment by Terrible-Tornado** [comment]
@eleybourn 
Thanks for your reply!
I tried to install the scanner app (Barcode Scanner from ZXing Team) and then the "Scan Barcode/ISBN" function worked well. Thank you!
But I just think that even without the scanner app installed, the app should not crash, instead, for example, something can be hinted.
Hope to be helpful.

**Comment by Grunthos** [comment]
This is also resolved in the current beta: no more need of external scanners.
